version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app # ローカルとコンテナ内の同期
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    stdin_open: true
  firestore:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "firebase emulators:start --only firestore"
