version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: gcloud app deploy
workflows:
  version: 2
  deploy: 
    jobs:
    - deploy
        
