version: 2
jobs:
  build: # ジョブ名
    docker:
      - image: circleci/node:lts-browsers # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout
      - run:
        name: Install node modules
        command: npm install
      - run:
        name: Build
        command: npm run build
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run:
        name: Install node modules
        command: npm install
      - run:
        name: deploy
        command: gcloud app deploy

workflows:
  build:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
