version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
        name: Set up gcloud config
        command: gcloud --quiet config set project ${GCLOUD_PROJECT}
      - run: gcloud -q app deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
