version: 2
jobs:
  build: # ジョブ名
    docker:
      - image: circleci/node:lts-browsers # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout
      - run:
        name: install package
        command: npm install
      - run:
        name: install firebase-tools
        command: npm install firebase-tools
      - run:
        name: install Firestore emulators
        command: npm run setup:emu:firestore
      - run:
        name: エミュレータの起動 & テスト実行
        command: npm run emu:start:firestore & sleep 10; npm run ci-test
workflows:
  test:
    jobs:
      - test
