version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: echo SKIP_PREFLIGHT_CHECK=true >> .env
      - run: npm install
      - run: CI=false npm run build
      - run: echo "export PATH=/Users/ryota/Downloads/google-cloud-sdk/bin/:$PATH" >> .bash_profile
      - run: source ~/.bash_profile
      - run: |
        echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: gcloud app deploy --no-promote --version $CIRCLE_SHA1 --quiet
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
