version: 2
jobs:
  build: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - run: echo "hello world"
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: npm install
      - run:
          name: emulators start
          command: firebase emulators:start --only firestore
      - run:
          name: Run Test
          command: npm run test
      # - run:
      #     name: deploy to Firebase Hosting
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
