version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run:
        name: Install node modules
        command: npm install
      - run:
        name: Build
        command: npm run build
      - run:
        name: deploy
        command: gcloud app deploy

workflows:
  version: 2
  jobs:
    - deploy:
        filters:
          branches:
            only:
              - master
