version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - run: rm package-lock.json && sed -e "/babel-jest/d" && sed -e "/eslint/d"
      - run: npm install
      - run: npm run build
      - run: gcloud app deploy --no-promote --version $CIRCLE_SHA1 --quiet
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
